test:
  a_table_with_a_really_long_name:
    limit: 300
    columns:
      id:
        field: number
        preview: number
        id: true
      slug:
        hidden: true
      content:
        passive: true
      success:
        field: number
        preview: number
  wp_many_columns:
    id: post_id
    columns:
      post_id:
        field: number
        preview: number
  jiddra:
  wp_many_columns:
    id: post_id
    columns:
      post_id:
        field: number
        preview: asda
phpmyadmin:
  pma__bookmark:
    hidden: true
  pma__users:
    hidden: true
world:
  city:
  country: